/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PcButton {
    }
    interface PcDropdown {
        /**
          * Where to append element
         */
        "appendTo": 'body' | 'current';
        /**
          * Should dropdown autoclose on changeValue
         */
        "autoClose": boolean;
        "autoFocus": boolean;
        "autocomplete": boolean;
        /**
          * Filter value
         */
        "currentFilter": any;
        /**
          * Define object mapping for id/value
         */
        "dataId": string;
        /**
          * Define object mapping for labels
         */
        "dataLabel": string;
        /**
          * Change value
         */
        "doChange": (val: any, originalEvent?: MouseEvent) => Promise<void>;
        /**
          * Close dropdown
         */
        "doClose": (isDisconnected?: boolean) => Promise<void>;
        /**
          * Open dropdown
         */
        "doOpen": () => Promise<void>;
        /**
          * Filter criteria
         */
        "filter": 'contains' | 'start';
        "hasFilter": boolean;
        "maxHeight": number;
        /**
          * Placeholder text
         */
        "placeholder": string;
        /**
          * Define object mapping for id/value
         */
        "source": any[];
        /**
          * Selected value
         */
        "value": any;
    }
    interface PcDropdownListItem {
        /**
          * Define object mapping for labels
         */
        "dataLabel": string;
        "isFocused": boolean;
        "refresh": (source: any[]) => Promise<void>;
        /**
          * Define object mapping for id/value
         */
        "sourceItems": any[];
    }
    interface PcModal {
    }
}
export interface PcDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPcDropdownElement;
}
export interface PcDropdownListItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPcDropdownListItemElement;
}
declare global {
    interface HTMLPcButtonElement extends Components.PcButton, HTMLStencilElement {
    }
    var HTMLPcButtonElement: {
        prototype: HTMLPcButtonElement;
        new (): HTMLPcButtonElement;
    };
    interface HTMLPcDropdownElement extends Components.PcDropdown, HTMLStencilElement {
    }
    var HTMLPcDropdownElement: {
        prototype: HTMLPcDropdownElement;
        new (): HTMLPcDropdownElement;
    };
    interface HTMLPcDropdownListItemElement extends Components.PcDropdownListItem, HTMLStencilElement {
    }
    var HTMLPcDropdownListItemElement: {
        prototype: HTMLPcDropdownListItemElement;
        new (): HTMLPcDropdownListItemElement;
    };
    interface HTMLPcModalElement extends Components.PcModal, HTMLStencilElement {
    }
    var HTMLPcModalElement: {
        prototype: HTMLPcModalElement;
        new (): HTMLPcModalElement;
    };
    interface HTMLElementTagNameMap {
        "pc-button": HTMLPcButtonElement;
        "pc-dropdown": HTMLPcDropdownElement;
        "pc-dropdown-list-item": HTMLPcDropdownListItemElement;
        "pc-modal": HTMLPcModalElement;
    }
}
declare namespace LocalJSX {
    interface PcButton {
    }
    interface PcDropdown {
        /**
          * Where to append element
         */
        "appendTo"?: 'body' | 'current';
        /**
          * Should dropdown autoclose on changeValue
         */
        "autoClose"?: boolean;
        "autoFocus"?: boolean;
        "autocomplete"?: boolean;
        /**
          * Filter value
         */
        "currentFilter"?: any;
        /**
          * Define object mapping for id/value
         */
        "dataId"?: string;
        /**
          * Define object mapping for labels
         */
        "dataLabel"?: string;
        /**
          * Filter criteria
         */
        "filter"?: 'contains' | 'start';
        "hasFilter"?: boolean;
        "maxHeight"?: number;
        /**
          * When value changed
         */
        "onChanged"?: (event: PcDropdownCustomEvent<{ val: any; originalEvent?: MouseEvent }>) => void;
        /**
          * Before element close, can be prevented
         */
        "onClose"?: (event: PcDropdownCustomEvent<any>) => void;
        /**
          * Before element open, can be prevented
         */
        "onOpen"?: (event: PcDropdownCustomEvent<any>) => void;
        /**
          * Placeholder text
         */
        "placeholder"?: string;
        /**
          * Define object mapping for id/value
         */
        "source"?: any[];
        /**
          * Selected value
         */
        "value"?: any;
    }
    interface PcDropdownListItem {
        /**
          * Define object mapping for labels
         */
        "dataLabel"?: string;
        "isFocused"?: boolean;
        "onChanged"?: (event: PcDropdownListItemCustomEvent<{ item: any; e: any }>) => void;
        /**
          * Define object mapping for id/value
         */
        "sourceItems"?: any[];
    }
    interface PcModal {
    }
    interface IntrinsicElements {
        "pc-button": PcButton;
        "pc-dropdown": PcDropdown;
        "pc-dropdown-list-item": PcDropdownListItem;
        "pc-modal": PcModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pc-button": LocalJSX.PcButton & JSXBase.HTMLAttributes<HTMLPcButtonElement>;
            "pc-dropdown": LocalJSX.PcDropdown & JSXBase.HTMLAttributes<HTMLPcDropdownElement>;
            "pc-dropdown-list-item": LocalJSX.PcDropdownListItem & JSXBase.HTMLAttributes<HTMLPcDropdownListItemElement>;
            "pc-modal": LocalJSX.PcModal & JSXBase.HTMLAttributes<HTMLPcModalElement>;
        }
    }
}
