/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PcEditor {
        "initialValue": string;
    }
    interface PcRenderer {
        "html": string;
        "mode": string;
    }
    interface PcStudio {
    }
    interface TestForAngular {
    }
}
export interface PcEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPcEditorElement;
}
declare global {
    interface HTMLPcEditorElement extends Components.PcEditor, HTMLStencilElement {
    }
    var HTMLPcEditorElement: {
        prototype: HTMLPcEditorElement;
        new (): HTMLPcEditorElement;
    };
    interface HTMLPcRendererElement extends Components.PcRenderer, HTMLStencilElement {
    }
    var HTMLPcRendererElement: {
        prototype: HTMLPcRendererElement;
        new (): HTMLPcRendererElement;
    };
    interface HTMLPcStudioElement extends Components.PcStudio, HTMLStencilElement {
    }
    var HTMLPcStudioElement: {
        prototype: HTMLPcStudioElement;
        new (): HTMLPcStudioElement;
    };
    interface HTMLTestForAngularElement extends Components.TestForAngular, HTMLStencilElement {
    }
    var HTMLTestForAngularElement: {
        prototype: HTMLTestForAngularElement;
        new (): HTMLTestForAngularElement;
    };
    interface HTMLElementTagNameMap {
        "pc-editor": HTMLPcEditorElement;
        "pc-renderer": HTMLPcRendererElement;
        "pc-studio": HTMLPcStudioElement;
        "test-for-angular": HTMLTestForAngularElement;
    }
}
declare namespace LocalJSX {
    interface PcEditor {
        "initialValue"?: string;
        "onChordProUpdated"?: (event: PcEditorCustomEvent<string>) => void;
    }
    interface PcRenderer {
        "html"?: string;
        "mode"?: string;
    }
    interface PcStudio {
    }
    interface TestForAngular {
    }
    interface IntrinsicElements {
        "pc-editor": PcEditor;
        "pc-renderer": PcRenderer;
        "pc-studio": PcStudio;
        "test-for-angular": TestForAngular;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pc-editor": LocalJSX.PcEditor & JSXBase.HTMLAttributes<HTMLPcEditorElement>;
            "pc-renderer": LocalJSX.PcRenderer & JSXBase.HTMLAttributes<HTMLPcRendererElement>;
            "pc-studio": LocalJSX.PcStudio & JSXBase.HTMLAttributes<HTMLPcStudioElement>;
            "test-for-angular": LocalJSX.TestForAngular & JSXBase.HTMLAttributes<HTMLTestForAngularElement>;
        }
    }
}
