/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PcsEditor {
        "initialValue": string;
    }
    interface PcsRenderer {
        "html": string;
        "mode": string;
    }
    interface PcsStudio {
    }
    interface TestForAngular {
    }
}
export interface PcsEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPcsEditorElement;
}
declare global {
    interface HTMLPcsEditorElement extends Components.PcsEditor, HTMLStencilElement {
    }
    var HTMLPcsEditorElement: {
        prototype: HTMLPcsEditorElement;
        new (): HTMLPcsEditorElement;
    };
    interface HTMLPcsRendererElement extends Components.PcsRenderer, HTMLStencilElement {
    }
    var HTMLPcsRendererElement: {
        prototype: HTMLPcsRendererElement;
        new (): HTMLPcsRendererElement;
    };
    interface HTMLPcsStudioElement extends Components.PcsStudio, HTMLStencilElement {
    }
    var HTMLPcsStudioElement: {
        prototype: HTMLPcsStudioElement;
        new (): HTMLPcsStudioElement;
    };
    interface HTMLTestForAngularElement extends Components.TestForAngular, HTMLStencilElement {
    }
    var HTMLTestForAngularElement: {
        prototype: HTMLTestForAngularElement;
        new (): HTMLTestForAngularElement;
    };
    interface HTMLElementTagNameMap {
        "pcs-editor": HTMLPcsEditorElement;
        "pcs-renderer": HTMLPcsRendererElement;
        "pcs-studio": HTMLPcsStudioElement;
        "test-for-angular": HTMLTestForAngularElement;
    }
}
declare namespace LocalJSX {
    interface PcsEditor {
        "initialValue"?: string;
        "onChordProUpdated"?: (event: PcsEditorCustomEvent<string>) => void;
    }
    interface PcsRenderer {
        "html"?: string;
        "mode"?: string;
    }
    interface PcsStudio {
    }
    interface TestForAngular {
    }
    interface IntrinsicElements {
        "pcs-editor": PcsEditor;
        "pcs-renderer": PcsRenderer;
        "pcs-studio": PcsStudio;
        "test-for-angular": TestForAngular;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pcs-editor": LocalJSX.PcsEditor & JSXBase.HTMLAttributes<HTMLPcsEditorElement>;
            "pcs-renderer": LocalJSX.PcsRenderer & JSXBase.HTMLAttributes<HTMLPcsRendererElement>;
            "pcs-studio": LocalJSX.PcsStudio & JSXBase.HTMLAttributes<HTMLPcsStudioElement>;
            "test-for-angular": LocalJSX.TestForAngular & JSXBase.HTMLAttributes<HTMLTestForAngularElement>;
        }
    }
}
