/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BmButton {
        "active"?: boolean;
        "color": "primary" | "secondary" | "minimal" | "destructive";
        "disabled"?: boolean;
        "endIcon"?: string;
        "loading"?: boolean;
        "size": "sm" | "base" | "lg" | "icon";
        "startIcon"?: string;
        "text"?: string;
    }
    interface BmButtonDropdown {
        /**
          * Should dropdown autoclose on changeValue
         */
        "autoClose": boolean;
        "autoFocus": boolean;
        "autocomplete": boolean;
        /**
          * Define object mapping for labels
         */
        "buttonLabel": string;
        /**
          * Filter value
         */
        "currentFilter": any;
        /**
          * Define object mapping for id/value
         */
        "dataId": string;
        /**
          * Define object mapping for labels
         */
        "dataLabel": string;
        /**
          * Change value
         */
        "doChange": (val: any, originalEvent?: MouseEvent) => Promise<void>;
        /**
          * Close dropdown
         */
        "doClose": (isDisconnected?: boolean) => Promise<void>;
        /**
          * Open dropdown
         */
        "doOpen": () => Promise<void>;
        /**
          * Optional ID for dropdown changed events
         */
        "dropdownId": string;
        /**
          * Filter criteria
         */
        "filter": 'contains' | 'start';
        "hasFilter": boolean;
        "maxHeight": number;
        /**
          * Placeholder text
         */
        "placeholder": string;
        /**
          * Define object mapping for id/value
         */
        "source": any[];
        /**
          * Selected value
         */
        "value": any;
    }
    interface BmButtonGroup {
        "combined": boolean;
        "containerProps": any;
    }
    interface BmDropdown {
        /**
          * Should dropdown autoclose on changeValue
         */
        "autoClose": boolean;
        "autoFocus": boolean;
        "autocomplete": boolean;
        /**
          * Filter value
         */
        "currentFilter": any;
        /**
          * Define object mapping for id/value
         */
        "dataId": string;
        /**
          * Define object mapping for labels
         */
        "dataLabel": string;
        /**
          * Change value
         */
        "doChange": (val: any, originalEvent?: MouseEvent) => Promise<void>;
        /**
          * Close dropdown
         */
        "doClose": (isDisconnected?: boolean) => Promise<void>;
        /**
          * Open dropdown
         */
        "doOpen": () => Promise<void>;
        /**
          * Optional ID for dropdown changed events
         */
        "dropdownId": string;
        /**
          * Filter criteria
         */
        "filter": 'contains' | 'start';
        "hasFilter": boolean;
        "maxHeight": number;
        /**
          * Placeholder text
         */
        "placeholder": string;
        /**
          * Define object mapping for id/value
         */
        "source": any[];
        /**
          * Selected value
         */
        "value": any;
    }
    interface BmDropdownListItem {
        /**
          * Define object mapping for labels
         */
        "dataLabel": string;
        "isFocused": boolean;
        "refresh": (source: any[]) => Promise<void>;
        /**
          * Define object mapping for id/value
         */
        "sourceItems": any[];
    }
    interface BmDropdownShell {
        /**
          * Should dropdown autoclose on changeValue
         */
        "autoClose": boolean;
        "autoFocus": boolean;
        "autocomplete": boolean;
        /**
          * Define object mapping for labels
         */
        "buttonLabel"?: string;
        /**
          * Filter value
         */
        "currentFilter": any;
        /**
          * Define object mapping for id/value
         */
        "dataId": string;
        /**
          * Define object mapping for labels
         */
        "dataLabel": string;
        /**
          * Change value
         */
        "doChange": (val: any, originalEvent?: MouseEvent) => Promise<void>;
        /**
          * Close dropdown
         */
        "doClose": (isDisconnected?: boolean) => Promise<void>;
        /**
          * Open dropdown
         */
        "doOpen": () => Promise<void>;
        /**
          * Optional ID for dropdown changed events
         */
        "dropdownId": string;
        /**
          * Filter criteria
         */
        "filter": 'contains' | 'start';
        "hasFilter": boolean;
        "maxHeight": number;
        /**
          * Placeholder text
         */
        "placeholder": string;
        /**
          * Define object mapping for id/value
         */
        "source": any[];
        /**
          * Selected value
         */
        "value": any;
    }
    interface BmEditor {
        "initialValue": string;
    }
    interface BmEditorHeader {
    }
    interface BmEditorSplitView {
    }
    interface BmTextEditor {
        "initialValue": string;
        "setCapo": (capoPosition: number) => Promise<void>;
    }
    interface BmView {
        "html": string;
        "mode": string;
    }
}
export interface BmButtonDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBmButtonDropdownElement;
}
export interface BmDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBmDropdownElement;
}
export interface BmDropdownListItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBmDropdownListItemElement;
}
export interface BmDropdownShellCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBmDropdownShellElement;
}
declare global {
    interface HTMLBmButtonElement extends Components.BmButton, HTMLStencilElement {
    }
    var HTMLBmButtonElement: {
        prototype: HTMLBmButtonElement;
        new (): HTMLBmButtonElement;
    };
    interface HTMLBmButtonDropdownElement extends Components.BmButtonDropdown, HTMLStencilElement {
    }
    var HTMLBmButtonDropdownElement: {
        prototype: HTMLBmButtonDropdownElement;
        new (): HTMLBmButtonDropdownElement;
    };
    interface HTMLBmButtonGroupElement extends Components.BmButtonGroup, HTMLStencilElement {
    }
    var HTMLBmButtonGroupElement: {
        prototype: HTMLBmButtonGroupElement;
        new (): HTMLBmButtonGroupElement;
    };
    interface HTMLBmDropdownElement extends Components.BmDropdown, HTMLStencilElement {
    }
    var HTMLBmDropdownElement: {
        prototype: HTMLBmDropdownElement;
        new (): HTMLBmDropdownElement;
    };
    interface HTMLBmDropdownListItemElement extends Components.BmDropdownListItem, HTMLStencilElement {
    }
    var HTMLBmDropdownListItemElement: {
        prototype: HTMLBmDropdownListItemElement;
        new (): HTMLBmDropdownListItemElement;
    };
    interface HTMLBmDropdownShellElement extends Components.BmDropdownShell, HTMLStencilElement {
    }
    var HTMLBmDropdownShellElement: {
        prototype: HTMLBmDropdownShellElement;
        new (): HTMLBmDropdownShellElement;
    };
    interface HTMLBmEditorElement extends Components.BmEditor, HTMLStencilElement {
    }
    var HTMLBmEditorElement: {
        prototype: HTMLBmEditorElement;
        new (): HTMLBmEditorElement;
    };
    interface HTMLBmEditorHeaderElement extends Components.BmEditorHeader, HTMLStencilElement {
    }
    var HTMLBmEditorHeaderElement: {
        prototype: HTMLBmEditorHeaderElement;
        new (): HTMLBmEditorHeaderElement;
    };
    interface HTMLBmEditorSplitViewElement extends Components.BmEditorSplitView, HTMLStencilElement {
    }
    var HTMLBmEditorSplitViewElement: {
        prototype: HTMLBmEditorSplitViewElement;
        new (): HTMLBmEditorSplitViewElement;
    };
    interface HTMLBmTextEditorElement extends Components.BmTextEditor, HTMLStencilElement {
    }
    var HTMLBmTextEditorElement: {
        prototype: HTMLBmTextEditorElement;
        new (): HTMLBmTextEditorElement;
    };
    interface HTMLBmViewElement extends Components.BmView, HTMLStencilElement {
    }
    var HTMLBmViewElement: {
        prototype: HTMLBmViewElement;
        new (): HTMLBmViewElement;
    };
    interface HTMLElementTagNameMap {
        "bm-button": HTMLBmButtonElement;
        "bm-button-dropdown": HTMLBmButtonDropdownElement;
        "bm-button-group": HTMLBmButtonGroupElement;
        "bm-dropdown": HTMLBmDropdownElement;
        "bm-dropdown-list-item": HTMLBmDropdownListItemElement;
        "bm-dropdown-shell": HTMLBmDropdownShellElement;
        "bm-editor": HTMLBmEditorElement;
        "bm-editor-header": HTMLBmEditorHeaderElement;
        "bm-editor-split-view": HTMLBmEditorSplitViewElement;
        "bm-text-editor": HTMLBmTextEditorElement;
        "bm-view": HTMLBmViewElement;
    }
}
declare namespace LocalJSX {
    interface BmButton {
        "active"?: boolean;
        "color"?: "primary" | "secondary" | "minimal" | "destructive";
        "disabled"?: boolean;
        "endIcon"?: string;
        "loading"?: boolean;
        "size"?: "sm" | "base" | "lg" | "icon";
        "startIcon"?: string;
        "text"?: string;
    }
    interface BmButtonDropdown {
        /**
          * Should dropdown autoclose on changeValue
         */
        "autoClose"?: boolean;
        "autoFocus"?: boolean;
        "autocomplete"?: boolean;
        /**
          * Define object mapping for labels
         */
        "buttonLabel"?: string;
        /**
          * Filter value
         */
        "currentFilter"?: any;
        /**
          * Define object mapping for id/value
         */
        "dataId"?: string;
        /**
          * Define object mapping for labels
         */
        "dataLabel"?: string;
        /**
          * Optional ID for dropdown changed events
         */
        "dropdownId"?: string;
        /**
          * Filter criteria
         */
        "filter"?: 'contains' | 'start';
        "hasFilter"?: boolean;
        "maxHeight"?: number;
        /**
          * When value changed
         */
        "onChanged"?: (event: BmButtonDropdownCustomEvent<{ val: any; id: string; originalEvent?: MouseEvent }>) => void;
        /**
          * Before element close, can be prevented
         */
        "onClose"?: (event: BmButtonDropdownCustomEvent<any>) => void;
        /**
          * Before element open, can be prevented
         */
        "onOpen"?: (event: BmButtonDropdownCustomEvent<any>) => void;
        /**
          * Placeholder text
         */
        "placeholder"?: string;
        /**
          * Define object mapping for id/value
         */
        "source"?: any[];
        /**
          * Selected value
         */
        "value"?: any;
    }
    interface BmButtonGroup {
        "combined"?: boolean;
        "containerProps"?: any;
    }
    interface BmDropdown {
        /**
          * Should dropdown autoclose on changeValue
         */
        "autoClose"?: boolean;
        "autoFocus"?: boolean;
        "autocomplete"?: boolean;
        /**
          * Filter value
         */
        "currentFilter"?: any;
        /**
          * Define object mapping for id/value
         */
        "dataId"?: string;
        /**
          * Define object mapping for labels
         */
        "dataLabel"?: string;
        /**
          * Optional ID for dropdown changed events
         */
        "dropdownId"?: string;
        /**
          * Filter criteria
         */
        "filter"?: 'contains' | 'start';
        "hasFilter"?: boolean;
        "maxHeight"?: number;
        /**
          * When value changed
         */
        "onChanged"?: (event: BmDropdownCustomEvent<{ val: any; id: string; originalEvent?: MouseEvent }>) => void;
        /**
          * Before element close, can be prevented
         */
        "onClose"?: (event: BmDropdownCustomEvent<any>) => void;
        /**
          * Before element open, can be prevented
         */
        "onOpen"?: (event: BmDropdownCustomEvent<any>) => void;
        /**
          * Placeholder text
         */
        "placeholder"?: string;
        /**
          * Define object mapping for id/value
         */
        "source"?: any[];
        /**
          * Selected value
         */
        "value"?: any;
    }
    interface BmDropdownListItem {
        /**
          * Define object mapping for labels
         */
        "dataLabel"?: string;
        "isFocused"?: boolean;
        "onItemChanged"?: (event: BmDropdownListItemCustomEvent<{ item: any; e: any }>) => void;
        /**
          * Define object mapping for id/value
         */
        "sourceItems"?: any[];
    }
    interface BmDropdownShell {
        /**
          * Should dropdown autoclose on changeValue
         */
        "autoClose"?: boolean;
        "autoFocus"?: boolean;
        "autocomplete"?: boolean;
        /**
          * Define object mapping for labels
         */
        "buttonLabel"?: string;
        /**
          * Filter value
         */
        "currentFilter"?: any;
        /**
          * Define object mapping for id/value
         */
        "dataId"?: string;
        /**
          * Define object mapping for labels
         */
        "dataLabel"?: string;
        /**
          * Optional ID for dropdown changed events
         */
        "dropdownId"?: string;
        /**
          * Filter criteria
         */
        "filter"?: 'contains' | 'start';
        "hasFilter"?: boolean;
        "maxHeight"?: number;
        /**
          * When value changed
         */
        "onChanged"?: (event: BmDropdownShellCustomEvent<{ val: any; id: string; originalEvent?: MouseEvent }>) => void;
        /**
          * Before element close, can be prevented
         */
        "onClose"?: (event: BmDropdownShellCustomEvent<any>) => void;
        /**
          * Before element open, can be prevented
         */
        "onOpen"?: (event: BmDropdownShellCustomEvent<any>) => void;
        /**
          * Placeholder text
         */
        "placeholder"?: string;
        /**
          * Define object mapping for id/value
         */
        "source"?: any[];
        /**
          * Selected value
         */
        "value"?: any;
    }
    interface BmEditor {
        "initialValue"?: string;
    }
    interface BmEditorHeader {
    }
    interface BmEditorSplitView {
    }
    interface BmTextEditor {
        "initialValue"?: string;
    }
    interface BmView {
        "html"?: string;
        "mode"?: string;
    }
    interface IntrinsicElements {
        "bm-button": BmButton;
        "bm-button-dropdown": BmButtonDropdown;
        "bm-button-group": BmButtonGroup;
        "bm-dropdown": BmDropdown;
        "bm-dropdown-list-item": BmDropdownListItem;
        "bm-dropdown-shell": BmDropdownShell;
        "bm-editor": BmEditor;
        "bm-editor-header": BmEditorHeader;
        "bm-editor-split-view": BmEditorSplitView;
        "bm-text-editor": BmTextEditor;
        "bm-view": BmView;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bm-button": LocalJSX.BmButton & JSXBase.HTMLAttributes<HTMLBmButtonElement>;
            "bm-button-dropdown": LocalJSX.BmButtonDropdown & JSXBase.HTMLAttributes<HTMLBmButtonDropdownElement>;
            "bm-button-group": LocalJSX.BmButtonGroup & JSXBase.HTMLAttributes<HTMLBmButtonGroupElement>;
            "bm-dropdown": LocalJSX.BmDropdown & JSXBase.HTMLAttributes<HTMLBmDropdownElement>;
            "bm-dropdown-list-item": LocalJSX.BmDropdownListItem & JSXBase.HTMLAttributes<HTMLBmDropdownListItemElement>;
            "bm-dropdown-shell": LocalJSX.BmDropdownShell & JSXBase.HTMLAttributes<HTMLBmDropdownShellElement>;
            "bm-editor": LocalJSX.BmEditor & JSXBase.HTMLAttributes<HTMLBmEditorElement>;
            "bm-editor-header": LocalJSX.BmEditorHeader & JSXBase.HTMLAttributes<HTMLBmEditorHeaderElement>;
            "bm-editor-split-view": LocalJSX.BmEditorSplitView & JSXBase.HTMLAttributes<HTMLBmEditorSplitViewElement>;
            "bm-text-editor": LocalJSX.BmTextEditor & JSXBase.HTMLAttributes<HTMLBmTextEditorElement>;
            "bm-view": LocalJSX.BmView & JSXBase.HTMLAttributes<HTMLBmViewElement>;
        }
    }
}
