name: Version or Publish

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          # ssh-key: ${{ secrets.SUBMODULE_CHORDSHEETJS_DEPLOY_KEY }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(GITHUB_REF#refs/tags/)

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: dotansimha/changesets-action@262e957f99be29087d2b13afa32a5d579bf1d080
        with:
          createGithubReleases: aggregate
          commit: "${{ steps.get_version.outputs.VERSION }}"
          githubReleaseName: "${{ steps.get_version.outputs.VERSION }}"
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Send a Slack notification if a publish happens
      #   if: steps.changesets.outputs.published == 'true'
      #   # You can do something when a publish happens.
      #   run: my-slack-bot send-notification --message "A new version of ${GITHUB_REPOSITORY} was published!"
